#! /bin/sh
#
# PLUCS server password change hook
#
# Copyright 2013-2014 it25 GmbH
#
# http://www.it25.de/
#
# All rights reserved. 
#
# The source code of this program is made available
# under the terms of the GNU Affero General Public License version 3
# (GNU AGPL V3) as published by the Free Software Foundation.
#
# In the case you use this program under the terms of the GNU AGPL V3,
# the program is provided in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License with the Debian GNU/Linux or Univention distribution in file
# /usr/share/common-licenses/AGPL-3; if not, see
# <http://www.gnu.org/licenses/>.

eval "$(ucr shell)"

if [ "$1" = "prechange" ] ; then
	PIDFILE=/var/run/ejabberd/ejabberd.pid
	if [ -f "${PIDFILE}" ] && kill -0 `cat ${PIDFILE}` ; then
		ucr set plucs/stoppedbyserverpasswordchange=yes
		echo "stopping ejabberd (plucs) due to upcoming server password change" | logger -t "server-password-change"
		invoke-rc.d plucs stop
	fi
fi

if [ "$1" = "postchange" -o "$1" = "nochange" ] ; then
	# update config file
	ucr commit /etc/ejabberd/ejabberd.cfg
	# start daemon only if it has been stopped by this script
	if [ "$plucs_stoppedbyserverpasswordchange" = "yes" ] ; then
		echo "starting ejabberd (plucs) after server password change" | logger -t "server-password-change"
		invoke-rc.d plucs start
		ucr unset plucs/stoppedbyserverpasswordchange
	fi
fi
